# Generated by Django 3.2 on 2021-05-21 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0032_auto_20210522_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 0, 13, 14, 950835)),
        ),
    ]
