# Generated by Django 3.2 on 2021-05-21 20:00

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0033_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 2, 0, 54, 913891)),
        ),
    ]
