# Generated by Django 3.2 on 2021-05-27 11:45

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0034_auto_20210522_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 45, 23, 110573)),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
