# Generated by Django 3.2 on 2021-05-27 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_english', '0035_auto_20210527_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_titel',
            name='subtitel_ar',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='head_titel',
            name='subtitel_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='head_titel',
            name='titel_ar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='head_titel',
            name='titel_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 18, 39, 13, 548418)),
        ),
    ]
